#!/bin/sh

TWOFASITE=$1
BASE=$HOME/.config/2fa

if [ -z "$TWOFASITE" -o "$TWOFASITE" = "help" ]; then
    echo "usage: 2fa site|list"
    echo ""
    echo "A TWOFA site is needed."
    echo ""
    echo "usage: 2fa site:"
    echo "	generate the 2 Factor for the site"
    echo "usage: 2fa list:"
    echo "	list the sites known"
    exit 1
fi

if [ "$TWOFASITE" = "list" ]; then
    for i in "$BASE"/*.oath; do
        site=$(basename "$i" .oath)
        if [ "$site" = "*" ]; then
            continue
        else
            echo "$site"
        fi
    done
    exit 0
fi

OATH=$BASE/$TWOFASITE.oath
if [ ! -f "$OATH" ]; then
    echo "Unable to find oath key for $TWOFASITE"
    exit 1
fi

OPTS=$BASE/$TWOFASITE.options
if [ ! -f "$OPTS" ]; then
    echo "Unable to find oath options for $TWOFASITE"
    exit 1
fi

oathtool "$(cat "$OPTS")" "$(cat "$OATH")"
